# KNK

Alkukuulustelun uudelleenrakennetut tärpit: https://knkalkukuulustelutarpit.netlify.app/

Tägit ovat luennoittain, mutta eivät seuraa samaa järjestystä kuin missä luennot pidetään. Järjestys onkin sen mukainen, miten itse suosittelen asiat opiskelemaan. 

## 01 Korvan rakenne, toiminta ja tavalliset poikkeavuudet

Pääasiassa vain kertausta C2:n Aistit-kurssilta. Diat riittävät, mutta jos jää epäselvyyksiä, niin voi katsoa seuraavia videoita:

- [Lyhyt tiivistelmä kuulemisen fysiologiasta](https://youtu.be/m_9SqIQ0BQQ?si=7wgRV4Af-paLQxU2)
- [Lyhyt tiivistelmä vestibulaarisysteemistä](https://youtu.be/ryGMI3SpxCE?si=9iWXNCKPqgmhWkNP)
- [Kaarikäytävien fysiologia](https://youtu.be/MMSG4cbNp_0?si=tgu1if6QFjuac9EK)
- [Utriculus ja sacculus](https://youtu.be/5iZAnn5HlVw?si=B9hhirLyV5Egct_C)

Kirjasta luento käsittelee 1.1. ja 1.2. sekä 1.10-kappaleesta "Ulko- ja välikorvan kehityshäiriöt"-osion. 

## 02 Korvakäytävätulehdus ja ympäröivien rakenteiden aiheuttamat korvan kiputilat {#Korvakaytavatulehdus}

Diat riittävät. TMD:n suhteen voi silmäillä [TMD:n käypä hoitoa](https://www.kaypahoito.fi/hoi50057), mutta ei tarvitse kovinkaan tarkasti osata tässä vaiheessa. 

Kirjasta luento käsittelee kappaleen 1.10 loppuun. 

## 03 Välikorvan sairaudet 1 {#Valikorva1}

Lue diojen lisäksi [tympanometriasta](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00740). Kannattaa lisäksi silmäillä seuraavia: 

- [Tärykalvoreikä-artikkelista osio traumaattinen tärykalvoreikä](https://www.terveysportti.fi/apps/dtk/ltk/article/duo11611/)
- [Tuba aperta-potilastapaus ja hoitosuosituksia](https://www.duodecimlehti.fi/duo10297)
- [Lasten välikorvatulehdusten Käypä Hoito](https://www.kaypahoito.fi/hoi31050)
- [AOM aikuisella](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00991/)
- SketchyPeds: Otitis media SOAP
 
Käsittelee kirjasta kappaleesta 1.11 osiot "Vammat", "Korvatorven toimintahäiriöt" ja "Äkillinen välikorvatulehdus (otitis media acuta)". myös "Välikorvatulehduksen komplikaatiot" ja sen alla olevat tarkemmat osiot komplikaatioista kannattaa lukea. Lisäksi suosittelen lukemaan kpl 1.5 "Immittanssimittaukset" (käsittelee tympanometrian perusteita). 

## 04 Välikorvan sairaudet 2 {#Valikorva2}

Käsittelee kroonisemmat välikorvaongelmat. Diat riittävät. Kannattaa lisäksi silmäillä seuraavia: 

- [Liimakorva-artikkeli](https://www.duodecimlehti.fi/duo18662)
- [Krooninen välikorvatulehdus, Terveysportti](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00992/)
- [Tärykalvoreikä; Terveysportti](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt02089/). Samoin [tämän artikkelin](https://www.terveysportti.fi/apps/dtk/ltk/article/duo11611/) voi lukea.

Käsittelee kirjan kappaleen 1.11. loppuun. 

## 05 Audiometria (Kuulokäyrän tulkinta ja erilaiset kuuloviat) {#Audiometria}

Ei sinänsä tarvitse lukea dioja eikä kirjaa (käsittelee kappaleen 1.4 "Äänes- ja puheaudiometria"). **Digicampuksen verkkokurssista osiot 1-3 riittää**; verkkokurssi on todella hyvä ja se kannattaa käydä läpi (kestää n. 30min). 

## 06 Kuulon suojaaminen, kuulo ja työ, tinnitus {#Kuulon-suojaaminen}

Diat sinänsä riittävät, tosin suosittelen lukemaan ehkä jopa niiden sijasta kirjasta kpl 1.12 osiot "Meluvamma" + "Äkillinen kuulonmenetys" + "Tinnitus". 

## 07 Korvaperäisen huimauksen diagnostiikka {#Korvaperaisen-huimauksen-diagnostiikka}

Käsittelee sekä neurologian kurssin luennon "Huimaus"; kortit ovat tägätty täysin samoin tähän kuin neuron alle -> lue molemmat diapaketit. Diojen ja huimausdemon ennakkomateriaalien lisäksi **suosittelen vahvasti katsomaan youtubesta Peter Johnsin videoita vertigosta;** erityisesti seuraavat videot ovat äärettömän hyviä: 

- [Big 3 of vertigo](https://youtu.be/MwbqJvMDonU?si=h--LtKuzrajJBFlT)
  - Käytännössä akuutin vertigon diagnostiikassa riittää, jos osaa diagnosoida BPPV:n ja vestibulaarineuriitin sekä epäillä strokea. On paljon muitakin huimauksen syitä, mutta nämä ovat selvästi tärkeimmät ja niiden erotusdiagnostinen algoritmi on osattava.   
  - Jos diagnoosi sopii näiden ulkopuolelle, niin voi miettiä mm. vestibulaarimigreeniä ja Menieren tautia. Usein on hyvä lähettää potilas vertigoekspertille tarkempaan arvioon; nämä muut diagnoosit eivät yleensä oikein ole aikapaineistettuja, joten ei haittaa vaikka ei keksisikään esim. Menieren taudin diagnoosia heti.
- [BPPV Dix Hallpike Test and Epley Maneuver](https://youtu.be/LxD-lgqix-s?si=m73_SsbD79vOCS8x)
  - [How to Diagnose and Treat Horizontal Canal BPPV](https://youtu.be/iOJOArGmepM?si=wmEc_hDiOYvNvh7X)
- [The HINTS exam](https://youtu.be/1q-VTKPweuk?si=uCtaqX3SXJKoptjl)
- [A Basic, Simplified Approach to the Dizzy Patient Part 1](https://youtu.be/9fQlnDLVeCE?si=J19Ils5NVXFQ56rC)
- [A Basic, Simplified Approach to the Dizzy Patient Part 2](https://youtu.be/FwUAUtm-_fM?si=hqeNRzIbKUWaDeRX)
- [Why you shouldn't do the HINTS exam on patients who DON'T have nystagmus](https://youtu.be/L4nOD8YdV-s?si=mFkUYMnclKZmmshc)
- [How to look very carefully for nystagmus by using a blank piece of paper](https://youtu.be/eGcUTfeHvZg?si=ADIZhZ5ySUx2k9a0)
- [Vestibular Migraine](https://youtu.be/XPIyXiv0UKg?si=wOTdml4O0axXaaOU)

Jos ei tykkää katsoa videoita, niin kannattaa ainakin lukea seuraavat artikkelit: [Constant vertigo and nystagmus algorithm](https://caep.ca/periodicals/Volume_22_Issue_4/Vol_22_Issue_4_Page_463_-_467_Johns.pdf) ja [HINTS masterclass](https://www.edguidelines.com/the-hints-exam-masterclass-how-to-understand-and-perform-perfectly/)

## 08 Lasten kuulon seulonta ja tutkiminen 

Diat riittävät. 

Kirjasta käsittelee kappaleet 1.6 "Okoakustiset emissiot", 1.7 "Lasten kuulotutkimukset", 1.8 "Sähköiset kuuloherätevasteet" ja 1.16 "Kuuloseulonnat". 

## 09 Kuuloapuvälineet ja kuulon kuntoutus {#Kuuloapuvalineet}

Diat riittävät. 

Kirjasta käsittelee kappaleen 1.17 "Kuulon kuntoutus". 

## 10 Kaulakyhmyt ja sylkirauhasen sairaudet 

Diat heikohkot, mutta riittävät sinänsä. Kannattaa silmäillä tarvittaessa seuraavia: 

- [Kivi sylkirauhasessa - mikä neuvoksi?](https://helda.helsinki.fi/server/api/core/bitstreams/fb765baa-7ca0-4ae3-a22d-46cea01c49a8/content)
- [Kyhmy kaulalla, Terveysportti](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00977/) ja samoin terveysportista [Lapsen suurentuneet imusolmukkeet ja muut kaulapatit](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00760/)
- [Aikuisen kaulapatti – miten tutkin, miten hoidan?](https://www.terveysportti.fi/apps/dtk/ltk/article/yll00076/)
- [Evaluation of a Neck Mass -luento Youtubessa](https://youtu.be/X6c1p6z9BjA?si=lANYNUXG4pFelAv9)

Kirjasta käsittelee kappaleen 4 "Sylkirauhaset" ja kappaleen 6 "Kaulan alueen sairaudet". 

## 11 Pään ja kaulan alueen pahanlaatuiset kasvaimet {#Paan-ja-kaulan-syovat}

Diat todella heikot. 

Kirjasta käsittelee kappaleen 7 "Pään ja kaulan alueen pahanlaatuiset kasvaimet". Käytännössä voi lukea vain kpl 7.1 "Yleistä pään ja kaulan alueen syövistä", sillä diapakettikin käsittelee pääasiassa vain pään ja kaulan alueen syöpien yleisiä perusteita. Suosittelen lukemaan sen mieluummin kuin pelkät diat.

- Eri osien syöpiä käsitellään vielä niiden omilla luennoillaan, joten esim. suuontelon, kurkunpään tuumorien ja nenän/sivuonteloiden tuumorien kortteja sitten tarkemmin sopivien luentojen alla. 

## 12 Suun limakalvomuutosten diagnostiikka 

Diat taas vähän huonot, mutta sinänsä riittävät. 

- [Suusyövän käypä hoito](https://www.kaypahoito.fi/hoi07025) kannattaa silmäillä läpi ainakin diagnostiikka-osioon asti. 

Kirjasta käsittelee kappaleen 3.10 "Suun sairaudet" ja 7.3 "Suuontelon ja huulen syöpä". Ainakin 3.10 kannattaa lukea. 

## 13 Nielemisvaikeus ja palan tunne  

Diat riittävät. Voi myös katsoa Moodlesta luentotallenteet. 

- Kortit tulevat ehkä vähän sekalaisessa järjestyksessä, koska ne ovat suoraan tägätty sisusten kurssilta tähän alle. 

Kirjasta käsittelee kappaleet 3.7 "Nieleminen" ja 3.16 "Nielemisvaikeus ja palantunne". 

## 14 Kurkunpään toiminta ja yleisimmät äänihäiriöitä aiheuttavat sairaudet {#Kurkunpaan-toiminta-ja-aanihairiosairaudet}

Diat riittävät. 

- Voi lisäksi lueskella ["Käheä ääni - missä vika"-artikkelin](https://helda.helsinki.fi/server/api/core/bitstreams/69fcc359-f2df-4eea-8c08-3ab8cc0323de/content)
- Ei pakollista katsoa, mutta [hyvä video erilaisista äänihäiriöistä](https://youtu.be/SwfrCKt1WaE?si=XbE-NibF0ER1W2A4)

Kirjasta käsittelee kappaleet 5.1-5.3 (Kurkunpään kehitys ja rakenne + Kurkunpään fysiologia + Kurkunpään tutkiminen), 5.5 "Kurkunpään tulehdustaudit", 5.8 "Äänihuulten hyvänlaatuiset muutokset" ja 7.6 "Kurkunpään syöpä". 

## 15 Äänihuulihalvaus ja muita neurologisia äänihäiriöitä {#Aanihuulihalvaus}

Diat riittävät, voi myös kattoa Moodlesta-löytyvän luentotallenteen. 

Kirjasta käsittelee kappaleet 5.1 "Kurkunpään kehitys ja rakenne" ja 5.6 "Kurkunpään toimintahäiriöt". 

## 16 Puheterapia 

Diat riittävät ja ne voi enemmänkin vain silmäillä läpi. Kortteina toimii vain muutamat terminologiakysymykset. 

## 17 Nenän anatomia ja toiminta {#Nenan-anatomia}

Katso "Nenän anatomia ja toiminta"-luentotallenne.

Kirjasta käsittelee kappaleet 2.1-2.3.

## 18 Nenän tukkoisuus {#Tukkoinen-nena}

Diat riittävät. Lisäksi voi silmäillä:

- [Terveysportista nenäpolyypit](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt01005/)
- [Terveysportista tukkoinen nenä](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt01006/)

Kirjasta käsittelee kappaleet 2.4 (sopivat osat eli "allerginen riniitti" - "ympäristöherkkyys..." + "nenänielun sairaudet" ja "granulomatoottiset sairaudet..."), 2.5 ja 2.7. 

## 19 Nenän sivuontelotulehdukset {#Rinosinuiitti}

Diat riittävät.

- [Sivuontelotulehduksen Käypä Hoito](https://www.kaypahoito.fi/hoi38050) kannattaa lukea. 

Kirjasta kpl 2.4 sopivilta osin: "Akuutti rinosinuiitti" - "Lapsen rinosinuiitti".  

## 20 KNK-radiologia perusterveydenhuollossa 

Diat riittävät, kannattaa myös silmäillä viime vuoden "Sinuskuvien tulkinta"-luento. 

## 21 Hammasperäinen infektio {#Hammasperainen-infektio}

Tässä luennossa käsitellään osittain samaa asiaa kuin seuraavassakin luennossa eli syviä kaulainfektioita. Saattaa olla hyvä lueskella molemmat diapaketit läpi ja tehdä kortit putkeen, mutta ne voi myös tehdä erillään toisistaan. Tämän luennon diat ovat tutkimuspainotteisia (eli heikkoja), mutta ne sinänsä riittävät. Lisäksi voi lukea: 

- [Artikkeli: Hammasperäinen infektio kaipaa toimenpiteitä – ei pelkkää antibioottia](https://www.terveysportti.fi/apps/dtk/ltk/article/yll00078/). Tämän voi melkein lukea luennon sijaan.  
- [Artikkeli: Mikrobilääkkeet hammasperäisten infektioiden hoidossa ja komplikaatioiden ehkäisyssä](https://www.terveysportti.fi/apps/dtk/ltk/article/hoi50090/). Tämä on myös hyvä ja kattava artikkeli aiheesta. 

## 22 Henkeä uhkaavat KNK-infektiot {#Henkea-uhkaavat-KNK-infektiot}

Diat riittävät. 

- Kannattaa kuitenkin lukea tämän artikkelin alkuosa [Silmäkuopan akuuteista tulehduksista](https://www.terveysportti.fi/apps/dtk/ltk/article/sll43384/), koska dioissa tämä aihe on hyvin epäselvästi opetettu. Myös tämä artikkeli: ["Simäluomen selluliitti ja orbitaselluliitti"](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00948/) kannattaa lukea. 
  - SketchyPeds löytyy myös aiheesta video
- ["Peritonsilliitti ja nielupaise"](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00984/) on myös hyvä artikkeli
  - SketchyPeds löytyy myös aiheesta video

Kirjasta luentoon sopiva osa on kpl 3.13:n "Peritonsilliitti ja nielupaise". 

## 23 Nielutulehdukset 

Diat riittävät. 

- [Nielutulehdusten Käypä Hoitoa](https://www.kaypahoito.fi/hoi38020) voi tarvittaessa selailla
- SketchyPeds löytyy aiheesta video. 

Kirjasta kpl 3.13

## 24 Risakirurgia 

Diat riittävät, lisäksi kannattaa katsoa luentotallenne: "Nielurisaleikkauksen jälkivuoto". 

Kirjasta käsittelee kpl 3.14. 

## 25 Kuorsaus ja uniapnea 

Luentotallenne riittää. 

- [Uniapnean Käypä Hoitoa](https://www.kaypahoito.fi/hoi50088) kannattaa selailla. 

Kirjasta käsittelee kpl 3.15. 

## 26 Kasvo- ja kuulohermo 

Diat riittävät. 

Kirjasta käsittelee kpl 1.13.