# Neuro

Tärpit löytyy: https://neurotarpit.netlify.app/

00_Neurologinen_status on täysin KLP:n korteista tägätty, ei ole sinänsä mitään uutta opiskeltavaa sen suhteen. 

## 01 Päänsärky 

Diat pääasiassa riittävät. 


## 02 Huimaus 

Käsittelee sekä KNK:n kurssin luennon "Korvaperäisen huimauksen diagnostiikka"; kortit ovat tägätty täysin samoin tähän kuin KNK:n alle -> lue molemmat diapaketit. Diojen ja huimausdemon ennakkomateriaalien lisäksi **suosittelen vahvasti katsomaan youtubesta Peter Johnsin videoita vertigosta;** erityisesti seuraavat videot ovat äärettömän hyviä: 

- [Big 3 of vertigo](https://youtu.be/MwbqJvMDonU?si=h--LtKuzrajJBFlT)
  - Käytännössä akuutin vertigon diagnostiikassa riittää, jos osaa diagnosoida BPPV:n ja vestibulaarineuriitin sekä epäillä strokea. On paljon muitakin huimauksen syitä, mutta nämä ovat selvästi tärkeimmät ja niiden erotusdiagnostinen algoritmi on osattava.   
  - Jos diagnoosi sopii näiden ulkopuolelle, niin voi miettiä mm. vestibulaarimigreeniä ja Menieren tautia. Usein on hyvä lähettää potilas vertigoekspertille tarkempaan arvioon; nämä muut diagnoosit eivät yleensä oikein ole aikapaineistettuja, joten ei haittaa vaikka ei keksisikään esim. Menieren taudin diagnoosia heti.
- [BPPV Dix Hallpike Test and Epley Maneuver](https://youtu.be/LxD-lgqix-s?si=m73_SsbD79vOCS8x)
  - [How to Diagnose and Treat Horizontal Canal BPPV](https://youtu.be/iOJOArGmepM?si=wmEc_hDiOYvNvh7X)
- [The HINTS exam](https://youtu.be/1q-VTKPweuk?si=uCtaqX3SXJKoptjl)
- [A Basic, Simplified Approach to the Dizzy Patient Part 1](https://youtu.be/9fQlnDLVeCE?si=J19Ils5NVXFQ56rC)
- [A Basic, Simplified Approach to the Dizzy Patient Part 2](https://youtu.be/FwUAUtm-_fM?si=hqeNRzIbKUWaDeRX)
- [Why you shouldn't do the HINTS exam on patients who DON'T have nystagmus](https://youtu.be/L4nOD8YdV-s?si=mFkUYMnclKZmmshc)
- [How to look very carefully for nystagmus by using a blank piece of paper](https://youtu.be/eGcUTfeHvZg?si=ADIZhZ5ySUx2k9a0)
- [Vestibular Migraine](https://youtu.be/XPIyXiv0UKg?si=wOTdml4O0axXaaOU)

Jos ei tykkää katsoa videoita, niin kannattaa ainakin lukea seuraavat artikkelit: [Constant vertigo and nystagmus algorithm](https://caep.ca/periodicals/Volume_22_Issue_4/Vol_22_Issue_4_Page_463_-_467_Johns.pdf) ja [HINTS masterclass](https://www.edguidelines.com/the-hints-exam-masterclass-how-to-understand-and-perform-perfectly/)

## 03 Aivoverenkiertohäiriöt (AVH) {#AVH}

Käsittää sekä AVH-luennon että seminaarin, käy molempien diat läpi. Verenvuotoja ei tämän tägin alla (SAV ja ICH löytyy pääasiassa tägin 23_Neurokirurgia_AVH alta), vaan keskitytty iskeemisiin aivoverenkiertohäiriöihin. 

- OnlineMedEd:llä on todella hyvä video strokesta; ei löydy laillisesti, mutta löytyy [täältä Telegrammiin ladattuna](https://t.me/s/USMLEOnlineMedED/187)

## 04 Tajuttomuus 

Diat sinänsä riittävät, vaikka ovatkin vähän köyhät.

- Kannattaa silmäillä [Tajuton potilas -artikkeli Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00870/) ja [Tajunnan häiriö -artikkeli Akuuttihoito-oppaasta](https://www.terveysportti.fi/apps/dtk/aho/article/aho00801). 
- Jos haluaa tarkemmin lueskella aiheesta, niin [oppikirjan Tajuttomuus-kappaleesta](https://www.oppiportti.fi/oppikirjat/neu00246) löytyy lisää

## 05 Uni- ja vireystilahäiriöt {#Uni-ja-vireystilahairiot}

Diat riittävät, samoja asioita käsitellään myös Psykiatrin kurssilla (kts. psykan tägi nro 11). Psykan kurssin alle on tägätty samat kortit kuin tähän tägiin ja niiden lisäksi myös unettomuutta käsitteleviä kortteja. 

## 06 Parkinsonin tauti ja muut liikehäirihäiriöt {#Parkinsonin-tauti}

Diat pääasiassa riittävät, tosin farmakologian suhteen kannattaa katsoa SketchyPharmin Parkinsonin lääkkeet -video. 

## 07 Etenevät muistisairaudet {#Etenevat-muistisairaudet}

Diat riittävät; SketchyPharmin Alzheimerin taudin lääkkeet -video kannattaa kuitenkin katsoa. 

## 08 Epilepsia 

Diat riittävät; SketchyPharmin videot epilepsialääkkeistä kannattaa kuitenkin katsoa. 

## 09 Keskushermoston infektiot 

Diat riittävät 

## 10 Sekavuus ja kohtaukselliset muistihäiriöt {#Sekavuus}

Diat riittävät

## 11 MS-tauti ja polyradikuliitti 

Diat pääasiassa riittävät, SketchyNeurolla on myös kaksi hyvää MS-videota. 

## 12 Ääreishermoston sairaudet {#Aareishermoston-sairaudet}

Kannattaa lukea myös KNF:n osion luennoista KNF 2 (ENMG). Aihealueet käsittelevät samoja asioita, joten tämä tägi sisältää molemmat luennot. 

- Terveysportin [Polyneuropatiat-artikkeli](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00925/) on hyvää luettavaa erotusdiagnostisten vaihtoehtojen läpikäymiseksi. 

Juurivauriot ja esim. Cauda Equina ovat merkattu punaisella oppimistavotteissa, mutta niitä ei kovinkaan paljoa näissä dioissa käydä läpi. Lisää niistä sitten neurokirurgian dioja käsittelevien tägien yhteydessä. 

## 13 Lihassairaudet 

Diat pääasiassa riittävät; monet matalan annin asioista löytää Patologian perusteet -oppikirjasta tai Terveysportista. Tietysti myös neurologia-oppikirjaa voi lukea. 

- [Lihasheikkous ja halvausoire -Terveysportti](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00867/)
- [Perinnölliset lihastaudit -Terveysportti](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00920/)

## 14 Aivovammat 

Lue sekä neurologian että neurokirurgian aivovammat-luentojen diat; ne riittävät. Lisätukena tietysti [aivovammojen Käypä Hoito](https://www.kaypahoito.fi/hoi18020)

## 15 Aivokasvaimet 

Lue sekä neurologian että neurokirurgian aivokasvaimet-luentojen diat; ne pääasiassa riittävät. Lisätukena tietysti oppikirjat ja terveysportti tai Patologian perusteet, jos haluaa oppia erityyppiset aivokasvaimet dioja tarkemmin. 

## 16 Toiminnalliset häiriöt {#Toiminnalliset-hairiot}

Diat riittää 

## 17 KNF1 (EEG ja herätevasteet) {#KNF1}

Diat riittää; tietysti hyvä olla käynyt jo epilepsia (tägi 08) läpi kokonaan omana aihepiirinään. 

## 18 KNF2 (ENMG)

Diat riittää; tietysti hyvä olla käynyt jo ääreishermoston sairaudet (tägi 12) läpi kokonaan omana aihepiirinään.

## 19 KNF 3 (Neuropaattinen kipu)

Diat riittää; tietysti hyvä olla käynyt jo ääreishermoston sairaudet (tägi 12) läpi kokonaan omana aihepiirinään.

## 20 KNF 4 (Kajoamattomat neuromodulaatiohoidot)

Diat riittää

## 21 Neuro-HIFU ja aivostimulaatio

Diat riittää

## 22 Funktionaalinen neurokirurgia 

Diat riittää

## 23 Neurokirurgia_AVH

Diat riittää. 

## 24 Hydrokefalus 

Diat riittää (tosin lisäsin tägin loppuun aiheeseen hyvin sopien kortteja idiopaattisesta intrakraniaalisesta hypertensiosta (IIH), jota ei dioissa käsitellä). 