# Psykiatria

## 01 Psykoosit 

Tägi käsittelee Psykoosit 1 ja 2. _En suosittele opiskelemaan ainoastaan dioista,_ koska ne ovat jokseenkin sekavat eivätkä auta luomaan selkeää kuvaa psykoosista ainakaan ensimateriaalina. Opiskelua myös häiritsee se, että käytössä on kolme eri diagnostista kriteeristöä: vielä käytössä oleva ICD-10, tulossa oleva ICD-11 (Suomessa vielä käytössä ICD-10; ICD-11 suunnitelmissa käyttöön 2028 kesästä alkaen) ja jenkeissä sekä tutkimuksissa käytössä oleva DSM-5. 

- Itse koen, että DSM-5-kriteeristö ja psykoosispektrumin luokittelu on näistä helpoimmin ymmärrettävissä, joten olen siihen nojannut korteissa tulevan ICD-11-luokituksen kanssa. ICD-10 ja sen monimutkainen skitsofreniaspektrin jaottelutapa tulee poistumaan lähivuosina suomalaisistakin suosituksista, joten en ole sitä availlut.  
- Skitsofrenian diagnoosin asettaa kuitenkin psykiatrian erikoislääkäri, joten kriteeristön tarkka hallinta ei ole vaadittua. Kriteeristön tietäminen kuitenkin auttaa mielestäni oireyhtymien ymmärtämisessä. 
  - Perusterveydenhuollon tehtävä on pääasiassa tunnistaa psykoosi ja psykoosiriski, selvittää mahdolliset somaattiset syyt psykoosille ja jatkaa hyvässä hoitotasapainossa olevan potilaan hoitoa.

**Erityisen hyvä opetusvideo (20 min) aiheesta löytyy [OnlineMedEdiltä](https://onlinemeded.org/spa/psychiatry/psychotic-disorders/acquire) laillisestikin ilmaiseksi.**

- Lisäksi kannattaa katsoa **psykoosilääkkeiden SketchyPharm-videot,** jos farmakologia on päässyt unohtumaan. 
- Voi myös silmäillä [skitsofrenian](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00840/) ja akuutin psykoosin [Terveysportti-artikkeleita](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt01694/) 
- Myös oppikirjasta voi lukea [Skitsofreniasta ja muista psykooseista](https://www.oppiportti.fi/oppikirjat/pkr00054). **Kannattaa lukea myös ainakin [katatoniasta](https://www.oppiportti.fi/oppikirjat/ysp03104), koska sen oireiden tunnistaminen on osa skitsofrenian (ja monien muiden psykiatristen häiriöiden) tunnistamista.**

Jos haluaa koulun materiaaleja selata lisää psykoosiin liittyen, niin tägiin kuuluu periaatteessa myös _psykoosidiat "Päivystyspsykiatria"-luennosta_

## 02 Mielialahäiriöt {#Mielialahairiot}

Tägi käsittelee Mielialahäiriöt 1 ja 2, kannattaa käydä ne molemmat läpi ennen kortteja (tai ainakin käydä 2 läpi sitten, kun alkaa hoitoon liittyviä kortteja ilmestymään). 

- OnlineMedEd:ltä löytyy telegrammista (tai laillisestikin ostamalla) kaksi hyvää mielialahäiriövideota: "Mood Disorders I" ja "Death, Dying & Babies"
- **SketchyPharmin masennuslääkevideot (ja mielialan tasaajien, erityisesti litiumin video) kannattaa katsoa myös, jos farmis päässyt unohtumaan. Näiden kortit on tägätty tähänkin, mutta ne on flägätty punaisella, jos niiden kertaaminen ei tunnu tarpeelliselta.**
- SketchyPsych:ltä löytyy kaksi videota, mutta ne vain käyvät läpi SIGECAPS- ja DIGFAST-muistisäännöt; eivät ole niin tärkeitä

[Masennuksen Käypä Hoito](https://www.kaypahoito.fi/hoi50023) kannattaa käydä läpi, samoin voi silmäillä [kaksisuuntaisen mielialahäiriön Käypä Hoitoa](https://www.kaypahoito.fi/hoi50076). 

## 03 Tarkkailulähete (M1) ja tahdosta riippumaton hoito {#M1}

Diat riittävät. 

## 04 Psykoterapiat 

Diat riittävät. 

## 05 Ahdistuneisuushäiriöt {#Ahdistuneisuushairiot}

Käsittelee Ahdistuneisuushäiriöt 1 ja 2. Diat sinänsä riittävät, mutta kannattaa katsoa OnlineMedED:ltä telegrammista videot "Anxiety disorders" ja "Obsessive Compulsive Disorders". 

## 06 Elimellisoireiset häiriöt {#Elimellisoireiset-hairiot}

Aiheen opiskelu on kamalaa sen takia, että jokaisessa kriteeristössä (ICD-10, ICD-11 ja DSM-5) oireyhtymät ovat luokiteltu eri tavalla ja ne eroavat toisistaan aika merkittävästi. Luentodiat käyvät tätä asiaa hieman läpi, mutta pelkkien diojen perusteella jää kuitenkin epäselvyyksiä, kun diat keskittyvät luonnollisesti enemmän ICD-10:n jaotteluun. 

- Yksittäisten oireyhtymien sijaan kuitenkin tärkein asia on ymmärtää aihepiiri ja miten sen kanssa kannattaa toimiaa. 

Tägin lopussa lisäksi hieman itse aiheutetuista häiriöistä (factitiuous disorders) ja simulaatiosta (tekosairaus, malingering), koska ne soveltuvat tähän osioon hyvin. Voi lukea kirjasta niitä käsittelevät kappaleet, mutta se ei sinänsä ole tarpeen: 

- [Oireiden tai vammojen tarkoituksellinen tuottaminen tai teeskentely](https://www.oppiportti.fi/oppikirjat/pkr00184)
- [Simulaatio](https://www.oppiportti.fi/oppikirjat/pkr00185)

OnlineMedEdiltä löytyy tästäkin video ja kannattaa katsoa se, vaikka se käsitteleekin oireyhtymät DSM-5-kriteeristön mukaan.

## 07 Persoonallisuushäiriöt {#Persoonallisuushairiot}

Opiskelua taas häiritsee diagnostisten luokitusten (ICD-10, -11 ja DSM-5) erot; kaikki luokittelevat häiriöt omalla tavallaan. 

- Kannattaa opetella pääasiassa DSM-5:n luokituksen kautta osittain sen takia, että se luokittelee häiriöt kivasti omiin luokkiinsa (A-, B- ja C-clusterit), ja myös osittain sen takia, että tämä on myös dioissa käytetty jako 
- Samojen häiriöiden diagnostiset kriteerit voivat erota ICD-10:n ja DSM-5:n välillä hieman, dioissa enemmän DSM-5:sta. 

Ainoa persoonallisuushäiriö, josta on tenteissä kysytty, on epävakaa persoonallisuushäiriö; varsinkin se kannattaa ottaa siis haltuun.

- HealthyGamerGG eli Dr. K on tehnyt [hyvän videon BPD:stä](https://youtu.be/6TS4d-zqRFA?si=GZKF1BlMXSyU0ihH)

Esimerkkihahmot korteissa ovat vähän animepainotteisia, koska sivistymättömyyteni takia en keksinyt yhtä helposti esimerkkejä muista mediatyypeistä. 

## 08 Päihdelääketiede I {#Paihdelaaketiede-I}

Diat riittävät. 

